# Build Stage
FROM golang:1.21.2-alpine3.18 as build

WORKDIR /starset-user-service

COPY userservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o starset-user-service

# Run Stage
FROM alpine:3.18

WORKDIR /starset-user-service

COPY --from=build /starset-user-service /app

EXPOSE 5001

CMD ["/app/starset-user-service"]