# Build Stage
FROM golang:1.21.2-alpine3.18 as build

WORKDIR /starset-order-service

COPY orderservice .

RUN go mod vendor

RUN CGO_ENABLED=0 go build -o starset-order-service

# Run Stage
FROM alpine:3.18

WORKDIR /starset-order-service

COPY --from=build /starset-order-service /app

EXPOSE 5003

CMD ["/app/starset-order-service"]